claimBlock: STONE
allowOverlap: false
maxSide: 128
protectFromExplosions: true

claimItem:
  name: "&aPrivateStone"
  lore:
    - "&7Поставь два камня, чтобы создать приват."
    - "&7Обычный камень не создаёт приват!"
  defaultGiveAmount: 2

# Авто-имя участка при создании
# Доступные плейсхолдеры: %n% (номер), %player% (ник владельца)
claimAutoNameFormat: "Участок %n% %player%"

messages:
  noPerm: "&cНет прав."
  onlyPlayers: "&cТолько для игроков."
  giveOk: "&aВыдано &e%amount%&a шт. предмета привата игроку &e%player%&a."
  firstCorner: "&eПервый угол установлен. Поставь второй камень привата."
  created: "&aПриват создан: &e%claimName% &7(&e%sizeX%x%sizeZ%&7)&a. Владелец: &e%owner%&a."
  tooLarge: "&cСлишком большой приват. Макс сторона: &e%max%&c."
  overlap: "&cПриват пересекается с существующим. Включи allowOverlap или выбери другое место."
  insideOther: "&cЭто зона привата игрока &e%owner%&c."
  removed: "&aПриват удалён (якорь сломан)."
  cantBreakAnchor: "&cНельзя ломать якорь чужого привата."
  trustOk: "&aТеперь игрок &e%player%&a доверен в этом привате."
  untrustOk: "&aИгрок &e%player%&a больше не доверен в этом привате."
  notInClaim: "&cТы не в привате."
  notOwner: "&cТы не владелец этого привата."
  info:
    - "&a--- &ePrivateStone &a---"
    - "&7Название: &e%claimName%"
    - "&7Владелец: &e%owner%"
    - "&7Размер: &e%sizeX%x%sizeZ%"
    - "&7Доверенные: &e%trusted%"
